FROM golang:1.22-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev sqlite

COPY go.mod go.sum ./
RUN go mod download
RUN GOTOOLCHAIN=auto go install golang.org/x/tools/cmd/goimports@latest
ENV PATH="/go/bin:${PATH}"

EXPOSE 12496

CMD ["go", "run", "./cmd/obsidian", "-no-ui"]
