#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="$ROOT_DIR/docs/current-state.md"
TMP_PROJECTS="$(mktemp)"
TMP_BOUNTIES="$(mktemp)"
TMP_BOARD="$(mktemp)"

cleanup() {
  rm -f "$TMP_PROJECTS" "$TMP_BOUNTIES" "$TMP_BOARD"
}
trap cleanup EXIT

if [[ ! -x "$ROOT_DIR/bin/au" ]]; then
  echo "error: missing executable $ROOT_DIR/bin/au" >&2
  exit 1
fi

"$ROOT_DIR/bin/au" list > "$TMP_PROJECTS"
"$ROOT_DIR/bin/au" bounty list > "$TMP_BOUNTIES"
"$ROOT_DIR/bin/au" bounty board > "$TMP_BOARD"

NOW_UTC="$(date -u +"%Y-%m-%d %H:%M:%SZ")"

{
  echo "# Current State"
  echo
  echo "Snapshot date: $NOW_UTC"
  echo
  echo "This file is generated by \`scripts/generate_current_state.sh\`."
  echo
  echo "## 1) Registered Projects"
  echo
  echo "Source: \`config/projects.tsv\`"
  echo
  echo "| Name | State | Path |"
  echo "|---|---|---|"
  awk 'NR > 2 && NF { name=$1; state=$2; path=$3; for(i=4;i<=NF;i++) path=path " " $i; printf("| `%s` | `%s` | `%s` |\n", name, state, path) }' "$TMP_PROJECTS"
  echo
  echo "## 2) Tracked Bounties"
  echo
  echo "Source: \`config/bounties.tsv\`"
  echo
  echo "| ID | Status | Progress | Priority | Owner | Project | Next Action |"
  echo "|---|---:|---:|---|---|---|---|"
  awk 'NR > 2 && NF { id=$1; status=$2; progress=$3; priority=$4; owner=$5; project=$6; nxt=$7; for(i=8;i<=NF;i++) nxt=nxt " " $i; printf("| `%s` | `%s` | `%s` | `%s` | `%s` | `%s` | %s |\n", id, status, progress, priority, owner, project, nxt) }' "$TMP_BOUNTIES"
  echo
  echo "## 3) Board View"
  echo
  echo '```text'
  cat "$TMP_BOARD"
  echo '```'
  echo
  echo "## 4) Quick Verification Commands"
  echo
  echo '```bash'
  echo "cd /home/administrator/projects/bountyOS/au-workspace"
  echo "./bin/au list"
  echo "./bin/au bounty list"
  echo "./bin/au bounty board"
  echo '```'
} > "$OUT_FILE"

echo "wrote: $OUT_FILE"
